name: Build latex book and upload artifact

# Controls when the action will run.
on:
  push:
    branches: ["main"]

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-book:
    runs-on: ubuntu-latest
    container: ghcr.io/scientificcomputing/latex-full:2023-11-07a
    steps:
      # Need newer image of latex-full to be able to bump checkout to v4
      - uses: actions/checkout@v4

      - name: Build PDF
        working-directory: book
        run: |
          make clean
          make

      - name: Upload book as artifact
        uses: actions/upload-artifact@v4
        with:
          name: book
          path: book/book.pdf
          if-no-files-found: error
          retention-days: 3
